# Site settings
baseurl = "https://juliazhan.github.io/"
languageCode = "en"
title = "julia's blog"
theme = "hugo-theme-cactus-plus"
# googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "julia"
	description = "stay hungry,stay foolish"
	bio = "a new and simple biography"

	# twitter = "your_twitter_id"
	# facebook = "your_facebook_id"

	enableRSS = false
	enableToc = true

	enableDisqus = true
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	# 摘要，发表的每篇博客的description为摘要
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = false
	enableBaiduAnalytics = true
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = '依然木紫允'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "home"
	about = "about"
	archive = "archive"
	#subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = "啊哦！找不到咯"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
	# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
	socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	# twitter-square = "https://www.twitter.com/nodejh"
	# github-square = "https://www.github.com/nodejh"


